#!/usr/bin/env node
// olivekit init [target] — apply the whole kit to ANY project in one command.
// This is the propagation mechanism: a CLAUDE.md written in the kit repo does NOT reach other
// projects; running this drops the rules + tokens + guardrail + registry config into the target,
// so Claude Code reads the house rules and stays on-system there too.
import { cpSync, mkdirSync, existsSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { resolve, join, relative, dirname, sep } from 'node:path';

const KIT = resolve(import.meta.dirname, '../..');
const [cmd, targetArg] = process.argv.slice(2);
const TARGET = resolve(targetArg || '.');

if (cmd !== 'init') {
  console.log('Usage: olivekit init [target-dir]');
  process.exit(cmd ? 1 : 0);
}

const isDir = (rel) => existsSync(join(TARGET, rel)) && statSync(join(TARGET, rel)).isDirectory();

// Detect the project's source roots up front so everything below adapts to the real layout
// instead of assuming a `src/` tree. Next.js app-router projects keep web code in app/ +
// components/ with no src/ at all; hardcoding `src` made the guardrail silently lint zero files.
// Scope to WEB UI dirs only — OliveKit is a web design system, so we deliberately skip lib/,
// engine/, bin/ etc.: CLI/backend code legitimately prints "·" and "—" and must not be flagged.
const SRC_CANDIDATES = ['src', 'app', 'components', 'pages', 'ui'];
const detectedSrcDirs = SRC_CANDIDATES.filter(isDir);
const lintTarget = detectedSrcDirs.length ? detectedSrcDirs.join(' ') : 'src';

// Detect the CSS entry the same way, so both components.json and the import wiring point at it.
const CSS_CANDIDATES = ['src/index.css', 'src/styles.css', 'src/app/globals.css', 'app/globals.css', 'styles/globals.css', 'src/styles/globals.css', 'src/app.css'];
const cssEntry = CSS_CANDIDATES.find((rel) => existsSync(join(TARGET, rel)));

console.log(`Applying OliveKit -> ${TARGET}\n`);
mkdirSync(TARGET, { recursive: true });
const created = [];

// 1. House rules live in a dedicated, fully-managed file; CLAUDE.md gets only a tiny pinned
//    pointer that @imports it. This avoids bloating a running project's CLAUDE.md or mixing the
//    design system into the team's own instructions, and lets an update just overwrite the
//    managed file (no surgery on anyone's CLAUDE.md, no duplicate-on-re-run).
const claudeDst = join(TARGET, 'CLAUDE.md');
const OK_HEADER = '<!-- Generated by OliveKit (olivekit init): managed file, re-running init overwrites it. Edit the kit, not this. -->';
mkdirSync(join(TARGET, '.claude'), { recursive: true });
const rulesDst = join(TARGET, '.claude/olivekit.md');
if (existsSync(rulesDst) && !readFileSync(rulesDst, 'utf8').startsWith('<!-- Generated by OliveKit')) {
  cpSync(rulesDst, `${rulesDst}.bak`);
  created.push('.claude/olivekit.md.bak (preserved an existing non-OliveKit file at that path)');
}
// Make doc references absolute (the target project has no docs/ tree of ours).
const RULES = readFileSync(join(KIT, 'CLAUDE.md'), 'utf8').replace(
  /`(docs\/[a-z0-9/-]+\.md)`/gi,
  '`https://github.com/TeamOliveCode/design-kit/blob/main/$1`',
);
writeFileSync(rulesDst, `${OK_HEADER}\n\n${RULES}`);
created.push('.claude/olivekit.md (house rules, managed)');

// Pin an idempotent reference in CLAUDE.md: insert once, replace between sentinels on update.
const OK_START = '<!-- olivekit:start -->';
const OK_END = '<!-- olivekit:end -->';
const ref = `${OK_START}\n## Design system (OliveKit)\nThis project uses **OliveKit**. For ALL UI work (pages, components, styling, copy) follow @.claude/olivekit.md, which is authoritative; do not deviate. Run \`npm run lint:design\` before showing UI.\n${OK_END}`;
let claudeCur = existsSync(claudeDst) ? readFileSync(claudeDst, 'utf8') : '';
if (claudeCur.includes(OK_START) && claudeCur.includes(OK_END)) {
  claudeCur = claudeCur.replace(new RegExp(`${OK_START}[\\s\\S]*?${OK_END}`), ref);
  created.push('CLAUDE.md (refreshed OliveKit reference)');
} else if (claudeCur.trim()) {
  claudeCur = `${claudeCur.trimEnd()}\n\n${ref}\n`;
  created.push('CLAUDE.md (added OliveKit reference, kept your content)');
} else {
  claudeCur = `${ref}\n`;
  created.push('CLAUDE.md (created with OliveKit reference)');
}
writeFileSync(claudeDst, claudeCur);

// 2. The token contract. Read from the committed registry (r/tokens.json embeds the CSS), so a
// `npx github:TeamOliveCode/design-kit init` run is self-contained; fall back to the local build.
mkdirSync(join(TARGET, 'olivekit'), { recursive: true });
const tokenFiles = existsSync(join(KIT, 'r/tokens.json'))
  ? JSON.parse(readFileSync(join(KIT, 'r/tokens.json'), 'utf8')).files
  : [
      { target: 'olivekit/tokens.css', content: readFileSync(join(KIT, 'packages/tokens/dist/tokens.css'), 'utf8') },
      { target: 'olivekit/theme.css', content: readFileSync(join(KIT, 'packages/tokens/dist/theme.css'), 'utf8') },
    ];
for (const f of tokenFiles) {
  writeFileSync(join(TARGET, f.target), f.content);
  created.push(f.target);
}

// 3. The deterministic guardrail + npm script.
mkdirSync(join(TARGET, 'scripts'), { recursive: true });
cpSync(join(KIT, 'scripts/lint-design.mjs'), join(TARGET, 'scripts/lint-design.mjs'));
created.push('scripts/lint-design.mjs');

const pkgPath = join(TARGET, 'package.json');
if (existsSync(pkgPath)) {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  pkg.scripts ||= {};
  if (!pkg.scripts['lint:design']) {
    pkg.scripts['lint:design'] = `node scripts/lint-design.mjs ${lintTarget}`;
    writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
    created.push(`package.json (added "lint:design" scoped to ${lintTarget})`);
  }
}

// 4. shadcn registry config so components pull by name.
const componentsJson = join(TARGET, 'components.json');
if (!existsSync(componentsJson)) {
  writeFileSync(
    componentsJson,
    `${JSON.stringify(
      {
        $schema: 'https://ui.shadcn.com/schema.json',
        style: 'new-york',
        tsx: true,
        tailwind: { css: cssEntry || 'src/styles.css', baseColor: 'neutral', cssVariables: true },
        aliases: { components: '@/components', ui: '@/components/ui', utils: '@/lib/utils' },
        registries: { '@olivekit': 'https://raw.githubusercontent.com/TeamOliveCode/design-kit/main/r/{name}.json' },
      },
      null,
      2,
    )}\n`,
  );
  created.push('components.json (with @olivekit registry)');
}

// 5. The olivekit-design skill, so Claude Code in this project gets the richer generation guidance.
const skillDir = join(TARGET, '.claude/skills/olivekit-design');
mkdirSync(skillDir, { recursive: true });
cpSync(join(KIT, 'skills/olivekit-design/SKILL.md'), join(skillDir, 'SKILL.md'));
created.push('.claude/skills/olivekit-design/SKILL.md');

// 6. Best-effort: wire the token imports into the detected CSS entry, with the correct relative path.
let cssWired = false;
if (cssEntry) {
  const p = join(TARGET, cssEntry);
  const css = readFileSync(p, 'utf8');
  if (!css.includes('olivekit/tokens.css')) {
    let rp = relative(dirname(p), join(TARGET, 'olivekit')).split(sep).join('/');
    if (!rp.startsWith('.')) rp = `./${rp}`;
    const imports = `@import "${rp}/tokens.css";\n@import "${rp}/theme.css";\n`;
    const next = css.includes('@import "tailwindcss"')
      ? css.replace(/(@import\s+["']tailwindcss["'][^\n]*\n)/, `$1${imports}`)
      : imports + css;
    writeFileSync(p, next);
    created.push(`${cssEntry} (wired token imports)`);
  }
  cssWired = true;
}

console.log('Created:');
for (const c of created) console.log(`  + ${c}`);
console.log('\nNext steps:');
let step = 1;
if (!cssWired) {
  console.log(`  ${step++}. In your main CSS, after \`@import "tailwindcss";\`, add (adjust the path to the olivekit/ folder):`);
  console.log('       @import "./olivekit/tokens.css";');
  console.log('       @import "./olivekit/theme.css";');
}
console.log(`  ${step++}. npx shadcn@latest add @olivekit/button @olivekit/card   (pull owned components)`);
console.log(`  ${step++}. npm run lint:design   (the guardrail — must pass; wire into CI + pre-commit)`);
console.log('\nRequires Tailwind v4 + React for components; the tokens (CSS variables) work in any stack.');
console.log('Claude Code now reads CLAUDE.md + the olivekit-design skill every session and stays on-system.');
